In [1]:
import pandas as pd
import requests
pd.set_option('display.max_columns', None) # for all columns in wide DataFrame
import time
import numpy as np

In [2]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2021-22&SeasonType=Regular%20Season&StatCategory=PTS'

In [3]:
r = requests.get(url=test_url).json()

In [4]:
col_names = r['resultSet']['headers']

In [5]:
pd.DataFrame(r['resultSet']['rowSet'], columns=col_names)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,1629027,1,Trae Young,1610612737,ATL,76,2652,711,1544,0.460,233,610,0.382,500,553,0.904,50,234,284,737,72,7,303,128,2155,2066,2.43,0.24
1,201942,2,DeMar DeRozan,1610612741,CHI,76,2743,774,1535,0.504,50,142,0.352,520,593,0.877,56,336,392,374,68,24,181,178,2118,1961,2.07,0.38
2,203954,3,Joel Embiid,1610612755,PHI,68,2296,666,1334,0.499,93,251,0.371,654,803,0.814,146,650,796,284,77,99,214,181,2079,2304,1.33,0.36
3,1628369,4,Jayson Tatum,1610612738,BOS,76,2731,708,1564,0.453,230,651,0.353,400,469,0.853,85,524,609,334,75,49,217,174,2046,1971,1.54,0.35
4,203999,5,Nikola Jokic,1610612743,DEN,74,2476,764,1311,0.583,97,288,0.337,379,468,0.810,206,813,1019,584,109,63,281,191,2004,2862,2.08,0.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,1630207,582,Nate Hinton,1610612754,IND,2,2,0,1,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,1,0,0,-2,0.00,0.00
601,1626155,582,Sam Dekker,1610612761,TOR,1,1,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
602,1629309,582,Trayvon Palmer,1610612765,DET,1,17,0,1,0.000,0,0,0.000,0,0,0.000,0,2,2,0,0,0,1,2,0,0,0.00,0.00
603,1629788,582,Tyler Hall,1610612752,NYK,1,2,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
604,1629597,582,Zylan Cheatham,1610612762,UTA,1,5,0,3,0.000,0,2,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-3,0.00,0.00

In [6]:
temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=col_names)
temp_df2 = pd.DataFrame({'Year':['2021-22' for i in range(len(temp_df1))],'Season_type':['Regular%20Season' for i in range(len(temp_df1))]})
temp_df3 = pd.concat([temp_df2, temp_df1], axis=1)

In [7]:
temp_df3

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2021-22,Regular%20Season,1629027,1,Trae Young,1610612737,ATL,76,2652,711,1544,0.460,233,610,0.382,500,553,0.904,50,234,284,737,72,7,303,128,2155,2066,2.43,0.24
1,2021-22,Regular%20Season,201942,2,DeMar DeRozan,1610612741,CHI,76,2743,774,1535,0.504,50,142,0.352,520,593,0.877,56,336,392,374,68,24,181,178,2118,1961,2.07,0.38
2,2021-22,Regular%20Season,203954,3,Joel Embiid,1610612755,PHI,68,2296,666,1334,0.499,93,251,0.371,654,803,0.814,146,650,796,284,77,99,214,181,2079,2304,1.33,0.36
3,2021-22,Regular%20Season,1628369,4,Jayson Tatum,1610612738,BOS,76,2731,708,1564,0.453,230,651,0.353,400,469,0.853,85,524,609,334,75,49,217,174,2046,1971,1.54,0.35
4,2021-22,Regular%20Season,203999,5,Nikola Jokic,1610612743,DEN,74,2476,764,1311,0.583,97,288,0.337,379,468,0.810,206,813,1019,584,109,63,281,191,2004,2862,2.08,0.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,2021-22,Regular%20Season,1630207,582,Nate Hinton,1610612754,IND,2,2,0,1,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,1,0,0,-2,0.00,0.00
601,2021-22,Regular%20Season,1626155,582,Sam Dekker,1610612761,TOR,1,1,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
602,2021-22,Regular%20Season,1629309,582,Trayvon Palmer,1610612765,DET,1,17,0,1,0.000,0,0,0.000,0,0,0.000,0,2,2,0,0,0,1,2,0,0,0.00,0.00
603,2021-22,Regular%20Season,1629788,582,Tyler Hall,1610612752,NYK,1,2,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,0,0.00,0.00
604,2021-22,Regular%20Season,1629597,582,Zylan Cheatham,1610612762,UTA,1,5,0,3,0.000,0,2,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-3,0.00,0.00

In [8]:
del temp_df1, temp_df2, temp_df3

In [9]:
df_cols = ['Year', 'Season_type'] + col_names

In [ ]:
df = pd.DataFrame(columns=df_cols)

season_types = ['Regular%20Season', 'Playoffs']

years = ['2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23', '2023-24']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        t_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=col_names)
        t_df2 = pd.DataFrame({'Year':[y for i in range(len(t_df1))],'Season_type':[s for i in range(len(t_df1))]})
        t_df3 = pd.concat([t_df2, t_df1], axis=1)
        df = pd.concat([df, t_df3], axis=0)

        print(f'Finished scraping data for the {y} {s}.')
        lag = np.random.uniform(low=5, high=30)
        print(f'...waiting {round(lag,1)} seconds')
        time.sleep(lag)
        
print(f'Process completed. Total run time: {round((time.time()-begin_loop)/60,2)}')

In [19]:
df.head()

,Year,Season_type,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,2013-14,Regular%20Season,201142,1,Kevin Durant,1610612760,OKC,81,3122,849,1688,0.503,192,491,0.391,703,805,0.873,58,540,598,445,103,59,285,174,2593,2572,1.56,0.36
1,2013-14,Regular%20Season,2546,2,Carmelo Anthony,1610612752,NYK,77,2982,743,1643,0.452,167,415,0.402,459,541,0.848,145,477,622,242,95,51,198,224,2112,1942,1.22,0.48
2,2013-14,Regular%20Season,2544,3,LeBron James,1610612748,MIA,77,2902,767,1353,0.567,116,306,0.379,439,585,0.750,81,452,533,488,121,26,270,126,2089,2255,1.81,0.45
3,2013-14,Regular%20Season,201567,4,Kevin Love,1610612750,MIN,77,2797,650,1421,0.457,190,505,0.376,520,633,0.821,224,739,963,341,59,35,196,136,2010,2328,1.74,0.30
4,2013-14,Regular%20Season,201933,5,Blake Griffin,1610612746,LAC,80,2863,718,1359,0.528,12,44,0.273,482,674,0.715,192,565,757,309,92,51,224,265,1930,2082,1.38,0.41

In [20]:
df.to_excel('nba_player_data.xlsx', index=false)